<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please enter your email address or mo_025e92</name>
   <tag></tag>
   <elementGuidId>c1433b25-632d-4292-877a-fcaa34cdefcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='identify_email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#identify_email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b543dc1-a05b-44e4-a473-d8898d07f6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>661cfa67-dcfb-496d-96f8-b78f1a3554ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputtext _9o1w</value>
      <webElementGuid>87fae499-ac02-4ac5-a81e-c9c48e00ac5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>identify_email</value>
      <webElementGuid>714c6ea2-f318-48c6-9526-b53a1de187eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>4c27769c-0ff2-4bb2-854d-bda4a06104d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email address or mobile number</value>
      <webElementGuid>a7171c54-d80e-4a81-af09-4ed6865fb6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autofocus</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5df9f0d5-25bd-48d6-8ec9-e5088b9f9f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Email address or mobile number</value>
      <webElementGuid>bc053442-5e61-4212-aaa2-004cdd6d65ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;identify_email&quot;)</value>
      <webElementGuid>4fc033d1-dfe7-42dc-acc1-b31da35679fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='identify_email']</value>
      <webElementGuid>61c0acec-727c-44fd-97d7-db64f10138d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='identify_yourself_flow']/div/div[2]/div/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>16fdd2e1-5bdc-4736-92ab-47bc9cb2e390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>d2d4624d-5319-46fd-87e5-4cc9faf2e466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'identify_email' and @name = 'email' and @placeholder = 'Email address or mobile number']</value>
      <webElementGuid>909287bd-8df0-4395-809c-2f06d0c01efa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
